apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: goserver
  newName: rhoghub/gitopsfc
  newTag: 19432fd431dc8d25982df02ca5f91cb7e20b8016
